pipeline:
    buildBuilder:
        image: denoland/deno:debian
        commands:
            - deno compile -A buildNode.ts
            - chmod a+x buildNode
    build:
        image: node:current-buster
        commands:
            - ./buildNode
    deploy:
        image: plugins/npm
        settings:
            username: ruthenic
            token:
                from_secret: NPM_API_KEY
            folder: npm
        when:
            event: tag

depends_on:
    - lint
    - test
