pipeline:
    buildBuilder:
        image: denoland/deno:debian
        commands:
            - deno compile -A buildNode.ts
    build:
        image: node:current-alpine3.16
        commands:
            - ls
    deploy:
        image: plugins/npm
        settings:
            token: NPM_API_KEY
            folder: npm
        secrets: [NPM_API_KEY]
        when:
            event: tag

depends_on:
    - lint
    - test
