pipeline:
    build:
        image: curlimages/curl:7.87.0
        commands:
            - curl -fsSL https://deno.land/x/install/install.sh | sh
            - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | sh
            - nvm install node
            - nvm use node
            - deno test -A buildNode.ts
    deploy:
        image: plugins/npm
        settings:
            token: NPM_API_KEY
            folder: npm
        secrets: [NPM_API_KEY]
        when:
            event: tag

depends_on:
    - lint
    - test
