pipeline:
    buildBuilder:
        image: denoland/deno:debian
        commands:
            - deno compile -A buildNode.ts
            - chmod a+x buildNode
    build:
        image: node:current-buster
        commands:
            - ls
            - $PWD/buildNode
    deploy:
        image: plugins/npm
        settings:
            token: NPM_API_KEY
            folder: npm
        secrets: [NPM_API_KEY]
        when:
            event: tag

depends_on:
    - lint
    - test
